spring:
  security:
    filter:
      disable-before-chain: false
  datasource:
    url: jdbc:postgresql://localhost:5432/wsn
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

        format_sql: true
    flyway:
      enabled: true
      locations: classpath:db/migration

server:
  port: 8082

app:
  jwt:
    secret: "weddingbazaar-secret-key-with-min-32-characters-1234567890"
    expiration-ms: 86400000 # 24 hours


