spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wsn
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresSQLDialect
        format_sql: true
    flyway:
      enabled: true
      locations: classpath:db/migration

server:
  port: 8081